In [8]:
y = [3,7]
z=[]

for n in y:
    z.append(2*n)

print(z)


[6, 14]


In [9]:
import numpy as np


a = np.array([3,7])

b=2*a
print(b) 

[ 6 14]


In [10]:
# Assignment-5: NumPy-1 


In [11]:
# Question-1

a = np.array([1,2,3,4,5])
b = a+2
c = 3*a
d= a/2



print(a, b, c)
print(d) 

[1 2 3 4 5] [3 4 5 6 7] [ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [12]:
# Question-2

from statistics import mode 

arr = np.array([1, 2, 3, 4, 5])
reversed =  arr[::-1]
print(reversed)

x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])


modex = np.argmax(np.bincount(x))
modey = np.argmax(np.bincount(y))

print(modex)
print(modey)




[5 4 3 2 1]
1
1


In [15]:
# Question-3 


import numpy as np

water = np.array([[10,20,30],
                  [40,50,60],
                  [70,80,90]])

element = water[1,2]
print(element)


60


In [16]:
# Question-4 


# Question-4 


aditya = np.linspace(10,100,25)

print(aditya)
print(aditya.ndim)
print(aditya.shape)
print(aditya.size)
print(aditya.dtype)
print(aditya.nbytes)

transpose_aditya = aditya.reshape(1,25)
print(transpose_aditya)

print(aditya.T)           


[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [17]:

# Question-5


ucs420_aditya = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])

print(ucs420_aditya)

mean = np.mean(ucs420_aditya)
median = np.median(ucs420_aditya)
maximum = np.max(ucs420_aditya)
minimum = np.min(ucs420_aditya)
unique = np.unique(ucs420_aditya)

print(mean)
print(median)
print(maximum)
print(minimum)
print(unique)

reshaped_ucs420_aditya = ucs420_aditya.reshape(4,3)

print(reshaped_ucs420_aditya)

resized_ucs420_aditya = np.resize(ucs420_aditya,(2,3))

print(resized_ucs420_aditya)


[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
